-- Add AI analysis columns to all document tables

-- Add to money_orders table
ALTER TABLE money_orders
ADD COLUMN IF NOT EXISTS ai_confidence NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ai_recommendation TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS fraud_risk_score NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS risk_level TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS model_confidence NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS anomaly_count INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS top_anomalies JSONB DEFAULT NULL;

-- Add to checks table
ALTER TABLE checks
ADD COLUMN IF NOT EXISTS ai_recommendation TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS fraud_risk_score NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS risk_level TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS model_confidence NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS anomaly_count INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS top_anomalies JSONB DEFAULT NULL;

-- Add to bank_statements table
ALTER TABLE bank_statements
ADD COLUMN IF NOT EXISTS ai_recommendation TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS fraud_risk_score NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS risk_level TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS model_confidence NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS anomaly_count INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS top_anomalies JSONB DEFAULT NULL;

-- Add to paystubs table
ALTER TABLE paystubs
ADD COLUMN IF NOT EXISTS ai_recommendation TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS fraud_risk_score NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS risk_level TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS model_confidence NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS anomaly_count INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS top_anomalies JSONB DEFAULT NULL;
